### ISSUE TITLE
Make pungi node smaller resources,   reduce preempt hit.

### ISSUE THREAD

**Issue by linux-modder** [fspin-k8s/fspin-infrastructure#7]
Present pungi node is a n1-standard16 (16 cpus and 60gb ram) which when running causes it to be a target for starving for other nodes to hit peak performance/throughput.

This proposed reduction would allow things on ALL nodes to be more streamlined and reduce the chance and impact of such starvation of extra resources.

**Comment by damaestro** [comment]
Thanks.
